### ISSUE TITLE
Uncaught (in promise) RangeError: Source is too large

### ISSUE THREAD

**Issue by Catsvilles** [etercast/mp3#1]
Uncaught (in promise) RangeError: Source is too large
    at Float32Array.set (<anonymous>)
    at Encoder.encode (mp3.js:328)

Tried to encode .wav files to mp3 by passing AudioBuffer channels data to the encoder. Tried with both channels, then with only one, tried more little audio files, used files from examples, then from the project folder, overall spent a few hours tweaking it. Any ideas why this is happening?
I'm on Ubuntu 18, latest Chrome 79

**Comment by AzazelN28** [comment]
I'm pretty sure this is happening because you're passing more samples than the ones you have setup in the encoder.

If you initialize the encoder this way:

```javascript
// You can also use Encoder.create()
const encoder = new Encoder({
  sampleRate: audioContext.sampleRate,
  samples: 2048,
  numChannels: 1
})
```

Then you should slice your AudioBuffer channels into multiple Float32Array buffers of 2048 samples maximum and then pass those buffers sequentially to the encoder.

```javascript
const leftChannelData = audioBuffer.getChannelData(0)
const rightChannelData = audioBuffer.getChannelData(1)

for (let index = 0; index < leftChannelData.length / 2048; index++) {
  const start = index * 2048
  const end = Math.min((index + 1) * 2048, leftChannelData.length)
  const slicedLeftChannelData = leftChannelData.slice(start, end)
  const slicedRightChannelData = rightChannelData.slice(start, end)
  const encodedMP3Frames = encoder.encode(
    slicedLeftChannelData, 
    slicedRightChannelData
  )
}
```

I hope this could be useful
